some macos bins

diff --git a/opget b/opget
--- a/opget
+++ b/opget
@@ -20,6 +20,14 @@ then
   exit 0
 fi
 
+# require 1password cli
+if ! [ -x "$(command -v op)" ];
+then
+  echo "error: opget relies on 'op' which is unavailable."
+  echo "see: https://support.1password.com/command-line"
+  exit 1
+fi
+
 ITEM=$1
 op get item ${ITEM} \
   | jq -r '.details.fields[] 
diff --git a/opsin b/opsin
--- a/opsin
+++ b/opsin
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# determine if called with source
+# first check if called via source
 if [[ $_ != $0 ]];
 then
   SOURCE=true
@@ -31,6 +31,14 @@ then
   else
     exit 0
   fi
+fi
+
+# require 1password cli
+if ! [ -x "$(command -v op)" ];
+then
+  echo "error: opget relies on 'op' which is unavailable."
+  echo "see: https://support.1password.com/command-line"
+  exit 1
 fi
 
 # require call via source
